### ISSUE TITLE
linode-linode -a create CoreOS incorrect boot profile

### ISSUE THREAD

**Issue by orme292** [linode/cli#72]
Deploying a CoreOS Linode via the CLI creates a configuration profile that boots to the Linode Kernel which causes kernel panics and a Lassie reboot cycle. Manually switching the boot profile to 'Direct Disk' resolves the issue and the Linode boots correctly.

linode-linode -a create -l testlinode -P P4ssWord -d CoreOs -p linode2048 --api-key _v3apikey_
linode-linode -a create -l testlinode -P P4ssWord -d CoreOS -p linode2048 --api-key _v3apikey_
linode-linode -a create -l testlinode -P P4ssWord -d "CoreOS Container Linux" -p linode2048 --api-key _v3apikey_

**Comment by displague** [comment]
This appears to be due to https://github.com/linode/cli/blob/72c56e6b3fdd001975bc36d4070356134d58fbb3/lib/Linode/CLI.pm#L899

Ideally, you would be able to specify `--kernel direct` (or `--kernelid 213`) to get around this, but `kernel` (while deeper option handling code would use it) is not accepting as a command line argument, AFAICT.

You can accomplish this, without specifying a kernel, with our APIv4 Linode CLI -- https://github.com/linode/linode-cli.

```
linode-cli create  -l testlinode -P $PASSWORD -d linode/containerlinux -L us-east-1a -p g5-nanode-1 --token $LINODE_PAT
```

or _rebuild_ with,
```
linode-cli linode rebuild   -P P4ssWord -d linode/containerlinux testlinode
```

**Comment by orme292** [comment]
https://github.com/linode/linode-cli/issues/13

**Comment by StefanLiebenberg** [comment]
The `-d linode/containerlinux` does not seem to be supported in the workaround. Looking at recent changes in that repo, it seems to be `-i` now

**Comment by displague** [comment]
Thanks for reporting this @orme292 and for the revised suggestion, @StefanLiebenberg, which made it back into my response.

This API v3 based CLI is deprecated in favor of the Linode API v4 based CLI at https://www.github.com/linode/linode-cli (pip install linode-cli).

Closing this issue as resolved through the new linode-cli.
